<?php
namespace beastbytes\wizard\models\wizard\survey;

class Cat extends CatDog
{
    protected $breeds = [
        'Abyssinian',
        'Aegean',
        'American Curl',
        'American Bobtail',
        'American Shorthair',
        'American Wirehair',
        'Arabian Mau',
        'Australian Mist',
        'Asian',
        'Asian Semi-longhair',
        'Balinese',
        'Bambino',
        'Birman',
        'Bombay',
        'Brazilian Shorthair',
        'British Semi-longhair',
        'British Shorthair',
        'British Longhair',
        'Burmese',
        'Burmilla',
        'California Spangled',
        'Chantilly-Tiffany',
        'Chartreux',
        'Chausie',
        'Cheetoh',
        'Colorpoint Shorthair',
        'Cornish Rex',
        'Cymric or Manx Longhair',
        'Cyprus',
        'Devon Rex',
        'Donskoy or Don Sphynx',
        'Dragon Li',
        'Dwarf cat or Dwelf',
        'Egyptian Mau',
        'European Shorthair',
        'Exotic Shorthair',
        'FoldEx Cat',
        'German Rex',
        'Havana Brown',
        'Highlander',
        'Himalayan or Colorpoint Persian',
        'Japanese Bobtail',
        'Javanese',
        'Kurilian Bobtail',
        'Khao Manee',
        'Korat',
        'Korean Bobtail',
        'Korn Ja',
        'Kurilian Bobtail or Kuril Islands Bobtail',
        'LaPerm',
        'Lykoi',
        'Maine Coon',
        'Manx',
        'Mekong Bobtail',
        'Minskin',
        'Munchkin',
        'Nebelung',
        'Napoleon',
        'Norwegian Forest Cat',
        'Ocicat',
        'Ojos Azules',
        'Oriental Bicolor',
        'Oriental Shorthair',
        'Oriental Longhair',
        'PerFold Cat',
        'Persian (Modern)',
        'Persian (Traditional)',
        'Peterbald',
        'Pixie-bob',
        'Raas',
        'Ragamuffin',
        'Ragdoll',
        'Russian Blue',
        'Russian White, Black and Tabby',
        'Sam Sawet',
        'Savannah',
        'Scottish Fold',
        'Selkirk Rex',
        'Serengeti',
        'Serrade petit',
        'Siamese',
        'Siberian',
        'Singapura',
        'Snowshoe',
        'Sokoke',
        'Somali',
        'Sphynx',
        'Thai',
        'Tonkinese',
        'Toyger',
        'Turkish Angora',
        'Turkish Van',
        'Ukrainian Levkoy'
    ];
}
